fix: Add missing Migration
monsieurbiz/SyliusShippingSlotPlugin pull request #20
Opened 2023-10-31 21:29 UTC by jacquesbh

2023-11-16 08:14 UTC, delyriand requested changes

2023-11-16 08:14 UTC, delyriand commented on src/Migrations/Version20231031212442.php
> +        $this->addSql('ALTER TABLE monsieurbiz_shipping_slot_config CHANGE rrules rrules JSON DEFAULT NULL');
<!-- Suggestions are specific requests to improve the subject under review. It is assumed that we all want to do what's best, so these comments are never dismissed as “mere suggestions”, but are taken seriously.  -->
**🎯 suggestion:** ‏I think it depends on the version of doctrine and mysql, we could do like Sylius: https://github.com/Sylius/Sylius/blob/336682edb5be6e2885bde0179816891315d89777/src/Sylius/Bundle/CoreBundle/Migrations/Version20211018130725.php

```suggestion
        $this->addSql('ALTER TABLE monsieurbiz_shipping_slot_config CHANGE rrules rrules LONGTEXT DEFAULT NULL');
```

2023-11-22 16:29 UTC, etienne-monsieurbiz requested changes
same as Mario

2024-03-13 13:46 UTC, delyriand commented on src/Migrations/Version20231031212442.php
> +        $this->addSql('ALTER TABLE monsieurbiz_shipping_slot_config CHANGE rrules rrules JSON DEFAULT NULL');
@jacquesbh I did it in the PR #21

2024-03-13 15:07 UTC, closed without merging